//
// DO NOT EDIT THIS FILE MANUALLY.
//
// This file is auto-generated by the 'sync-types.sh' script.
// Any manual changes will be overwritten the next time the script is run.
//
// Generated on: Sun Feb  1 19:53:36 PKT 2026
//


