"""Add timestamps to Task model

Revision ID: 519ab3f4353d
Revises: 63f279eb6ccb
Create Date: 2026-01-07 19:56:12.098119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519ab3f4353d'
down_revision: Union[str, Sequence[str], None] = '63f279eb6ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    # ### end Alembic commands ###
