"""add jwks table

Revision ID: 84518683b9ac
Revises: 9ad74ee46c57
Create Date: 2026-01-12 22:36:09.665767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84518683b9ac'
down_revision: Union[str, Sequence[str], None] = '9ad74ee46c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publicKey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privateKey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwks')
    # ### end Alembic commands ###
