#!/bin/bash
#
# Auto-generates TypeScript interfaces from backend Pydantic models.
#
# This script ensures that the frontend's data types are always in sync
# with the backend's data models, enforcing the 'Zero-Manual-Code'
# principle for type safety across the stack.
#
# Dependencies:
#   - pydantic-to-typescript: Must be installed in the environment.
#
# Usage:
#   ./scripts/sync-types.sh
#

set -e

# --- Configuration ---
BACKEND_MODELS_DIR="backend/app/models"
FRONTEND_TYPES_FILE="frontend/src/types/models.ts"
TEMP_TYPES_FILE=$(mktemp)

# --- Header for Auto-Generated File ---
HEADER_CONTENT="//
// DO NOT EDIT THIS FILE MANUALLY.
//
// This file is auto-generated by the 'sync-types.sh' script.
// Any manual changes will be overwritten the next time the script is run.
//
// Generated on: $(date)
//

"

# --- Main Logic ---

# Check if the backend models directory exists
if [ ! -d "$BACKEND_MODELS_DIR" ]; then
  echo "✅ Backend models directory '$BACKEND_MODELS_DIR' not found. Skipping type generation."
  # Create an empty file with the header if it doesn't exist
  if [ ! -f "$FRONTEND_TYPES_FILE" ]; then
    echo "$HEADER_CONTENT" > "$FRONTEND_TYPES_FILE"
    echo "Generated empty types file at '$FRONTEND_TYPES_FILE'."
  fi
  exit 0
fi

echo "🔄 Generating TypeScript interfaces from Pydantic models..."

# Add local node_modules binary to PATH
export PATH="$PWD/frontend/node_modules/.bin:$PATH"

# Run the conversion tool
cd backend
export PYTHONPATH=.
uv run pydantic2ts \
  --module "app.models.models" \
  --output "../$TEMP_TYPES_FILE"
cd ..

# Prepend the header to the generated file
{ echo "$HEADER_CONTENT"; cat "$TEMP_TYPES_FILE"; } > "$FRONTEND_TYPES_FILE"

# --- Cleanup ---
rm "$TEMP_TYPES_FILE"

echo "✅ TypeScript interfaces generated successfully at '$FRONTEND_TYPES_FILE'."
