apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | toString | b64enc | quote }}
  ALEMBIC_DATABASE_URL: {{ .Values.secrets.ALEMBIC_DATABASE_URL | toString | b64enc | quote }}
  CORS_ORIGINS: {{ .Values.secrets.CORS_ORIGINS | toString | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | toString | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | toString | b64enc | quote }}
  OPENAI_BASE_URL: {{ .Values.secrets.OPENAI_BASE_URL | toString | b64enc | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.secrets.NEXT_PUBLIC_API_URL | toString | b64enc | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.secrets.NEXT_PUBLIC_APP_URL | toString | b64enc | quote }}
  BETTER_AUTH_URL: {{ .Values.secrets.BETTER_AUTH_URL | toString | b64enc | quote }}
  BETTER_AUTH_USE_SECURE_COOKIES: {{ .Values.secrets.BETTER_AUTH_USE_SECURE_COOKIES | toString | b64enc | quote }}